### ISSUE TITLE
url oficial del proyecto: programador

### ISSUE THREAD

**Issue by robertocabellon** [cdrfiuba/programador#2]
En la pagina del proyecto "Programador" en el sitio del labi https://labi.fi.uba.ar/labi/programador creo que el enlace al sitio oficial deberia direccionar a una subpagina de la del club, algo asi como:  clubderobotica.com.ar/programador.

**Comment by MisaelK** [comment]
Veo que esto caducó... el sitio de LABi hasta cambió de manos ya.
